# Deploy snapshots to Sonatpe OSS repository and deploy site to GitHub Pages

name: Deploy

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Check out Git repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Configure GIT
      - name: Configure GIT
        run: |
          git config --global user.email "${{ secrets.GH_SITE_DEPLOY_EMAIL }}"
          git config --global user.name "${{ secrets.GH_SITE_DEPLOY_NAME }}"

      # Set up environment with Java and Maven
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 8
          cache: 'maven'

      # Build, deploy to ossrh, generate and stage site
      - name: Build, verify, deploy, generate site
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        run: ./mvnw -s ./.maven-settings.xml -Pcontinuous-integration -B -U clean deploy site

      # Deploy site to Github Pages
      # WORKAROUND for https://issues.apache.org/jira/browse/MSCMPUB-18 - deploy site in multiple steps for subset of modules
      - name: Stage and deploy site - Part 1
        run: >
          ./mvnw -s ./.maven-settings.xml -Pcontinuous-integration -B site:stage scm-publish:publish-scm
          --projects '.,parent,commons,url,link'
          -Dscmpublish.checkinComment="Maven site: ${{ github.repository }} - Part 1"
          -Dusername=${{ secrets.GH_SITE_DEPLOY_USERNAME }}
          -Dpassword=${{ secrets.GH_SITE_DEPLOY_PAT }}
      - name: Stage and deploy site - Part 2
        run: >
          ./mvnw -s ./.maven-settings.xml -Pcontinuous-integration -B site:stage scm-publish:publish-scm
          --projects '!parent,!commons,!url,!link'
          -Dscmpublish.checkinComment="Maven site: ${{ github.repository }} - Part 2"
          -Dusername=${{ secrets.GH_SITE_DEPLOY_USERNAME }}
          -Dpassword=${{ secrets.GH_SITE_DEPLOY_PAT }}
